[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss12"

    [buildPlans.IosevkaCustom.variants.design]
    one = "base"
    two = "curly-neck-serifless"
    three = "two-arcs"
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    six = "closed-contour"
    seven = "bend-serifless"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "oval-dotted"
    capital-a = "round-top-serifless"
    capital-g = "toothed-serifless-hooked"
    capital-j = "serifed"
    capital-m = "hanging-serifless"
    capital-q = "curly-tailed"
    capital-w = "straight-vertical-sides-serifless"
    f = "serifless"
    g = "single-storey-serifless"
    i = "tailed"
    j = "serifless"
    l = "tailed"
    m = "earless-corner-double-arch-short-leg-serifless"
    t = "bent-hook"
    w = "rounded-vertical-sides-serifless"
    y = "cursive-flat-hook-serifless"